{{- $deployment := .Values.deployment | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ .Values.project }}-{{ .Values.env }}
  labels: 
    app: fastapi-demo
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
      - name: {{ $deployment.containers.name }}
        image: "{{ $deployment.containers.image.name }}:{{ $deployment.containers.image.tag }}"
        ports:
        - containerPort: {{ $deployment.containers.port }}
        env:
        - name: USER
          value: "Diego Lins"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000