project: k8s
env: lab
account: "651644924182"
deployment:
  name: fastapi-demo
  labels:
    app: fastapi-demo
  replicas: 1
  containers:
    name: fastapi-demo
    image:
      name: 651644924182.dkr.ecr.us-east-1.amazonaws.com/fastapi-demo
      tag: 0.3-arm@sha256:68753fea441cf5b7d8f0b691402fe34c5b0b5b82ab7baf8c396ac712c8971b80
    port: 8000

service:
  name: fastapi-demo
  type: ClusterIP
  port: 80
  targetPort: 8000
  
serviceAccount:
  name: fastapi-demo

# ingress:
#   hosts: portela.testmyapi.xyz
#   gateway: 
#     name: fastapi-demo
#     servers:
#       port:
#         number: 80
#         name: http
#         protocol: HTTP

#   virtualService:
#     name: fastapi-demo
#     route:
#       destination:
#         host: fastapi-demo.k8s-lab.svc.cluster.local

