project: "k8s"
env: "lab"

deployment:
  name: "fastapi-demo"
  labels:
    app: "fastapi-demo"
  replicas: "1"
  containers:
    name: "fastapi-demo"
    image:
      name:
      tag:
    port: 8000

service:
  name: "fastapi-demo"
  type: ClusterIP
  port: 80
  targetPort: 8000
  
serviceAccount:
  name:

ingress:
  hosts: portela.testmyapi.xyz
  gateway: 
    name: "fastapi-demo"
    servers:
      port:
        number: 80
        name: http
        protocol: HTTP

  virtualService:
    name: "fastapi-demo"
    route:
      destination:
        host: fastapi-demo.k8s-lab.svc.cluster.local

