{{- $serviceAccount := .Values.serviceAccount | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  namespace: {{ .Values.project }}-{{ .Values.env }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.account }}:role/Devops-jamorim