# kubernetes/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.project }}-{{ .Values.env }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432