{{- $deployment := .Values.deployment | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ .Values.project }}-{{ .Values.env }}
  labels: 
    app: fastapi-demo
    provisioner: demo-arm
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
        provisioner: demo-arm
    spec:
      nodeSelector:
        provisioner: demo-arm
      serviceAccountName: fastapi-demo
      containers:
      - name: {{ $deployment.containers.name }}
        image: "{{ $deployment.containers.image.name }}:{{ $deployment.containers.image.tag }}"
        ports:
        - containerPort: {{ $deployment.containers.port }}
        env:
        - name: USER
          value: portela
      tolerations:
      - key: "provisioner"
        operator: "Equal"
        value: "demo-arm"
        effect: "NoSchedule"