project: k8s
env: vinicius
account: "651644924182"
deployment:
  name: fastapi-demo
  labels:
    app: fastapi-demo
  replicas: 1
  containers:
    name: fastapi-demo
    image:
      name: 651644924182.dkr.ecr.us-east-1.amazonaws.com/fastapi-demo
      tag: amd@sha256:2ed0c255216e6ffb397e20968bc6ac1810e0e32cf04f1c2c2960ea0eb6280ef7
    port: 8000

service:
  name: fastapi-demo
  type: ClusterIP
  port: 80
  targetPort: 8000
  
serviceAccount:
  name: fastapi-demo



    