apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.48.0
    helm:
      values: |
        admin:
          existingSecret: "grafana-access"
          userKey: admin-user
          passwordKey: admin-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true