apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-components
  namespace: argocd
spec:
  project: default #every application belongs to a single project
  source:
    repoURL: https://github.com/Valcann/Kubernetes-EKS-Lab.git
    targetRevision: HEAD
    path: istio-components
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
