apiVersion: v1
kind: Secret
metadata:
  name: grafana-access
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: ZDIyRjljcU9CQVBRTGZHS2FFc09iMUxPNXN0ZDBhQU16dDJJV2o2TQ==