apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portela-app
  namespace: argocd
spec:
  destination:
    namespace: k8s-lab
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: modelo
    repoURL: https://github.com/Valcann/Kubernetes-EKS-Lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
