project: k8s
env: jamorim
account: "651644924182"
deployment:
  name: fastapi-demo
  labels:
    app: fastapi-demo
  replicas: 1
  containers:
    name: fastapi-demo
    image:
      name: 651644924182.dkr.ecr.us-east-1.amazonaws.com/fastapi-demo
      tag: 0.1-arm@sha256:ee161add82e5547742b2dab02cb78a9d897843ebc8fdcb4039de6babd40777f8
    port: 8000

service:
  name: fastapi-demo
  type: ClusterIP
  port: 80
  targetPort: 8000
  
serviceAccount:
  name: jamorim
